export const tokens = {
  colors: {
    verdant: {
      50: 'var(--verdant-50)',
      100: 'var(--verdant-100)',
      200: 'var(--verdant-200)',
      300: 'var(--verdant-300)',
      400: 'var(--verdant-400)',
      500: 'var(--verdant-500)',
      600: 'var(--verdant-600)',
      700: 'var(--verdant-700)',
      800: 'var(--verdant-800)',
      900: 'var(--verdant-900)',
      950: 'var(--verdant-950)',
    },
    stone: {
      50: 'var(--stone-50)',
      100: 'var(--stone-100)',
      200: 'var(--stone-200)',
      300: 'var(--stone-300)',
      400: 'var(--stone-400)',
      500: 'var(--stone-500)',
      600: 'var(--stone-600)',
      700: 'var(--stone-700)',
      800: 'var(--stone-800)',
      900: 'var(--stone-900)',
      950: 'var(--stone-950)',
    },
    aurora: 'var(--aurora-500)',
    lichen: 'var(--lichen-500)',
    citron: 'var(--citron-500)',
  },
  typography: {
    display: 'var(--font-display)',
    sans: 'var(--font-sans)',
    mono: 'var(--font-mono)',
  },
  spacing: {
    tight: '0.5rem',
    snug: '0.75rem',
    cozy: '1rem',
    comfortable: '1.5rem',
    spacious: '2rem',
    loose: '3rem',
  },
  radii: {
    sm: 'var(--radius-sm)',
    md: 'var(--radius-md)',
    lg: 'var(--radius-lg)',
    xl: 'var(--radius-xl)',
    '2xl': 'var(--radius-2xl)',
    pill: 'var(--radius-pill)',
  },
  easings: {
    in: 'var(--ease-verdant-in)',
    out: 'var(--ease-verdant-out)',
    inOut: 'var(--ease-verdant-in-out)',
    springSoft: 'var(--ease-spring-soft)',
    springBounce: 'var(--ease-spring-bounce)',
  }
};
